In [1]:
import numpy as np

In [17]:
data = np.array([[1,1,-1],
       [1,2,-1],
        [1,2,1],
        [1,1,1],
        [1,1,-1],
        [2,1,-1],
        [2,2,-1],
        [2,2,1],
        [2,3,1],
        [2,3,1],
        [3,3,1],
        [3,2,1],
        [3,2,1],
        [3,3,1],
        [3,3,-1],
       ])
X = np.array(data[:,0:1])
Y = np.array(data[:,2])

In [22]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(X, Y).predict(X)
print("Number of mislabeled points out of a total %d points : %d"
      % (X.shape[0],(Y != y_pred).sum()))

[-1 -1  1  1 -1 -1 -1  1  1  1  1  1  1  1 -1]
[-1 -1 -1 -1 -1  1  1  1  1  1  1  1  1  1  1]
Number of mislabeled points out of a total 15 points : 5


In [24]:
from sklearn.naive_bayes import BernoulliNB
gnb = BernoulliNB()
y_pred = gnb.fit(X, Y).predict(X)
print("Number of mislabeled points out of a total %d points : %d"
      % (X.shape[0],(Y != y_pred).sum()))

[-1 -1  1  1 -1 -1 -1  1  1  1  1  1  1  1 -1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
Number of mislabeled points out of a total 15 points : 6


In [25]:
from sklearn.naive_bayes import MultinomialNB
gnb = MultinomialNB()
y_pred = gnb.fit(X, Y).predict(X)
print("Number of mislabeled points out of a total %d points : %d"
      % (X.shape[0],(Y != y_pred).sum()))

[-1 -1  1  1 -1 -1 -1  1  1  1  1  1  1  1 -1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
Number of mislabeled points out of a total 15 points : 6
